import { Category, Product, Testimonial, Promotion, BusinessProfile } from './types';
import { Utensils, Beef, Beer, IceCream, Coffee, Pizza, Sandwich, Wine, Soup, Apple, Cake, Martini, Fish, Salad, Leaf, Clock, Package, Drumstick, Droplets, CookingPot, ChefHat } from 'lucide-react';

import { PRODUCT_IMAGES } from './productImages';

export const ICON_MAP: Record<string, any> = {
  Utensils,
  Beef,
  Beer,
  IceCream,
  Coffee,
  Pizza,
  Sandwich,
  Wine,
  Soup,
  Apple,
  Cake,
  Martini,
  Fish,
  Salad,
  Leaf,
  Clock,
  Package,
  Drumstick,
  Droplets,
  CookingPot,
  ChefHat
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'marmitas', name: 'Marmitas Fit', icon: 'Utensils' },
  { id: 'lasanhas', name: 'Lasanhas', icon: 'CookingPot' },
  { id: 'coxinhas', name: 'Coxinhas', icon: 'Drumstick' },
  { id: 'molhos', name: 'Molhos', icon: 'Droplets' },
  { id: 'caldos', name: 'Caldos e Sopas', icon: 'Soup' },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Coxinhas
  {
    id: 'cox-1',
    categoryId: 'coxinhas',
    name: 'Coxinha de Frango Fit',
    description: 'Recheada com queijo. Opção com e sem glúten. Feita na airfryer. Oferta: 1 un por R$ 9,00 ou 3 un por R$ 24,00!',
    price: 9.00,
    image: 'https://ais-studio-build-user-uploads.s3.us-east-1.amazonaws.com/fe1b00dc-5c1d-4ceb-b6ec-f2af240bbd08/image_1712045051.png',
    available: true,
    type: 'pronta-entrega',
  },
  // Marmitas Tradicionais
  {
    id: 'mar-trad-1',
    categoryId: 'marmitas',
    name: 'Arroz branco, frango em cubos e legumes',
    description: '500g. Arroz branco soltinho com cubos de frango grelhados e mix de legumes da estação.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-2',
    categoryId: 'marmitas',
    name: 'Arroz branco, carne moída e legumes',
    description: '500g. Arroz branco com carne moída magra refogada e legumes variados.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-3',
    categoryId: 'marmitas',
    name: 'Purê de cenoura com frango em cubos e brócolis',
    description: '500g. Purê de cenoura aveludado, frango em cubos e brócolis cozido no vapor.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-4',
    categoryId: 'marmitas',
    name: 'Purê de cenoura com carne moída e brócolis',
    description: '500g. Purê de cenoura, carne moída magra e brócolis fresco.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-5',
    categoryId: 'marmitas',
    name: 'Escondidinho de aipim com carne moída',
    description: '500g. Massa de aipim cremosa recheada com carne moída magra.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-6',
    categoryId: 'marmitas',
    name: 'Escondidinho de aipim com frango desfiado',
    description: '500g. Massa de aipim cremosa recheada com frango desfiado temperado.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-7',
    categoryId: 'marmitas',
    name: 'Escondidinho de aipim com carne de panela',
    description: '500g. Massa de aipim cremosa recheada com carne de panela desfiada suculenta.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-8',
    categoryId: 'marmitas',
    name: 'Escondidinho de batata doce com frango',
    description: '500g. Massa de batata doce recheada com frango desfiado.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-9',
    categoryId: 'marmitas',
    name: 'Escondidinho de batata doce com carne moída',
    description: '500g. Massa de batata doce recheada com carne moída magra.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-10',
    categoryId: 'marmitas',
    name: 'Escondidinho de batata doce com carne de panela',
    description: '500g. Massa de batata doce recheada com carne de panela desfiada.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-11',
    categoryId: 'marmitas',
    name: 'Escondidinho de abóbora com carne moída',
    description: '500g. Massa de abóbora cabotiá recheada com carne moída magra.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-12',
    categoryId: 'marmitas',
    name: 'Escondidinho de abóbora com frango',
    description: '500g. Massa de abóbora cabotiá recheada com frango desfiado.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-13',
    categoryId: 'marmitas',
    name: 'Escondidinho de abóbora com carne de panela',
    description: '500g. Massa de abóbora cabotiá recheada com carne de panela desfiada.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-14',
    categoryId: 'marmitas',
    name: 'Escondidinho de batata inglesa com carne moída',
    description: '500g. Massa de batata inglesa recheada com carne moída magra.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-15',
    categoryId: 'marmitas',
    name: 'Escondidinho de batata inglesa com frango',
    description: '500g. Massa de batata inglesa recheada com frango desfiado.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-16',
    categoryId: 'marmitas',
    name: 'Macarrão integral à bolonhesa',
    description: '500g. Macarrão integral com molho bolonhesa artesanal de carne magra.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-17',
    categoryId: 'marmitas',
    name: 'Macarrão integral com frango ao molho de tomate',
    description: '500g. Macarrão integral com frango desfiado e molho de tomate artesanal.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-18',
    categoryId: 'marmitas',
    name: 'Panqueca de frango com molho de tomate',
    description: '500g. Duas panquecas recheadas com frango e cobertas com molho de tomate.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-19',
    categoryId: 'marmitas',
    name: 'Panqueca de carne moída com molho de tomate',
    description: '500g. Duas panquecas recheadas com carne moída e cobertas com molho de tomate.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-20',
    categoryId: 'marmitas',
    name: 'Arroz integral, feijão, carne moída e legumes',
    description: '500g. Prato completo com arroz integral, feijão carioca, carne moída e legumes.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-trad-21',
    categoryId: 'marmitas',
    name: 'Arroz integral, feijão, frango e legumes',
    description: '500g. Prato completo com arroz integral, feijão carioca, frango em cubos e legumes.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-1',
    categoryId: 'marmitas',
    name: 'Strogonoff de frango fit',
    description: '500g. Strogonoff de frango com creme de leite light, arroz branco e batata rústica assada na airfryer.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
    ingredients: ['Peito de frango', 'Creme de leite light', 'Champignon', 'Arroz branco', 'Batata rústica'],
  },
  {
    id: 'mar-2',
    categoryId: 'marmitas',
    name: 'Risoto de frango',
    description: '500g. Risoto cremoso de frango desfiado, ervilhas frescas e temperos naturais.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
    ingredients: ['Arroz arbóreo', 'Frango desfiado', 'Ervilhas frescas', 'Parmesão light', 'Cebola', 'Alho'],
  },
  {
    id: 'mar-3',
    categoryId: 'marmitas',
    name: 'Yakisoba fit',
    description: '500g. Macarrão integral com legumes crocantes e tiras de frango suculentas ao molho shoyu light.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-4',
    categoryId: 'marmitas',
    name: 'Almôndegas com molho de tomate e purê de batata',
    description: '500g. Almôndegas de patinho com molho de tomate artesanal e purê de batata cremoso.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
    ingredients: ['Carne moída (patinho)', 'Batata', 'Molho de tomate artesanal', 'Leite desnatado', 'Temperos'],
  },
  {
    id: 'mar-5',
    categoryId: 'marmitas',
    name: 'Almôndegas com macarrão e molho de tomate',
    description: '500g. Almôndegas de patinho com molho de tomate artesanal e macarrão integral.',
    price: 21.00,
    image: PRODUCT_IMAGES['mar-5'] || 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
    ingredients: ['Carne moída (patinho)', 'Macarrão integral', 'Molho de tomate artesanal', 'Manjericão'],
  },
  {
    id: 'mar-6',
    categoryId: 'marmitas',
    name: 'Arroz com cenoura e filé de frango acebolado',
    description: '500g. Arroz com cenoura e filé de frango acebolado suculento.',
    price: 21.00,
    image: PRODUCT_IMAGES['mar-6'] || 'https://images.unsplash.com/photo-1594973557371-75971b7c6cce?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-7',
    categoryId: 'marmitas',
    name: 'Arroz com brócolis e filé de frango ao molho de mostarda',
    description: '500g. Arroz com brócolis e filé de frango ao molho de mostarda especial.',
    price: 21.00,
    image: PRODUCT_IMAGES['mar-7'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-8',
    categoryId: 'marmitas',
    name: 'Panqueca de espinafre com carne ao molho branco',
    description: '500g. Panqueca de espinafre recheada com carne ao molho branco cremoso.',
    price: 21.00,
    image: PRODUCT_IMAGES['mar-8'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-9',
    categoryId: 'marmitas',
    name: 'Panqueca de espinafre com frango ao molho branco',
    description: '500g. Panqueca de espinafre recheada com frango ao molho branco cremoso.',
    price: 21.00,
    image: PRODUCT_IMAGES['mar-9'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-10',
    categoryId: 'marmitas',
    name: 'Polenta com ragu de carne de panela',
    description: '500g. Polenta cremosa com ragu de carne de panela desfiada.',
    price: 21.00,
    image: PRODUCT_IMAGES['mar-10'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-11',
    categoryId: 'marmitas',
    name: 'Carreteiro fit',
    description: '500g. Arroz carreteiro tradicional em versão fit com carnes magras.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'mar-12',
    categoryId: 'marmitas',
    name: 'Purê de batata inglesa com frango à parmegiana fit',
    description: '500g. Purê de batata inglesa com frango à parmegiana fit (empanado e assado).',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  // Lasanhas
  {
    id: 'las-1',
    categoryId: 'lasanhas',
    name: 'Lasanha de Berinjela Fit',
    description: '500g. Lasanha de berinjela com molho de tomate artesanal, queijo branco e manjericão.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1619895092538-128341789043?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
    ingredients: ['Berinjela', 'Molho de tomate artesanal', 'Queijo branco light', 'Manjericão fresco'],
  },
  {
    id: 'las-2',
    categoryId: 'lasanhas',
    name: 'Lasanha à Bolonhesa Integral',
    description: '500g. Massa integral, carne moída magra, molho de tomate artesanal e queijo light.',
    price: 21.00,
    image: 'https://images.unsplash.com/photo-1560717845-968823efbee1?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
  // Caldos
  {
    id: 'cal-1',
    categoryId: 'caldos',
    name: 'Caldo Verde Fit',
    description: '500g. Tradicional caldo verde com couve fresca, batata e paio light.',
    price: 18.00,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
    ingredients: ['Couve manteiga', 'Batata', 'Paio light', 'Caldo de legumes natural', 'Alho'],
  },
  {
    id: 'cal-2',
    categoryId: 'caldos',
    name: 'Creme de Aipim com Frango',
    description: '500g. Creme aveludado de aipim com frango desfiado e temperos naturais.',
    price: 18.00,
    image: 'https://images.unsplash.com/photo-1594759077573-218329ec7d85?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
    ingredients: ['Aipim (mandioca)', 'Frango desfiado', 'Cebolinha', 'Salsa', 'Temperos naturais'],
  },
  {
    id: 'cal-3',
    categoryId: 'caldos',
    name: 'Sopa de Feijão com Macarrão',
    description: '500g. Sopa nutritiva de feijão com macarrão e legumes.',
    price: 18.00,
    image: PRODUCT_IMAGES['cal-3'] || 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
    ingredients: ['Feijão carioca', 'Macarrão ave-maria integral', 'Cenoura', 'Chuchu', 'Temperos'],
  },
  {
    id: 'cal-4',
    categoryId: 'caldos',
    name: 'Caldo de Feijão com Bacon',
    description: '500g. Caldo de feijão batido com pedacinhos de bacon light.',
    price: 18.00,
    image: PRODUCT_IMAGES['cal-4'] || 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'cal-5',
    categoryId: 'caldos',
    name: 'Creme de Abóbora com Carne',
    description: '500g. Creme de abóbora cabotiá com carne desfiada suculenta.',
    price: 18.00,
    image: PRODUCT_IMAGES['cal-5'] || 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'cal-6',
    categoryId: 'caldos',
    name: 'Caldo de Lentilha',
    description: '500g. Caldo de lentilha nutritivo (com ou sem calabresa).',
    price: 18.00,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'cal-7',
    categoryId: 'caldos',
    name: 'Caldo de Abóbora com Alho Poró',
    description: '500g. Creme leve de abóbora com o toque especial do alho poró.',
    price: 18.00,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'cal-8',
    categoryId: 'caldos',
    name: 'Canja de Galinha',
    description: '500g. Tradicional canja de galinha com legumes e arroz.',
    price: 18.00,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  {
    id: 'cal-9',
    categoryId: 'caldos',
    name: 'Caldo de Batata com Alho Poró e Bacon',
    description: '500g. Caldo cremoso de batata com alho poró e bacon crocante.',
    price: 18.00,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'pronta-entrega',
  },
  // Molhos
  {
    id: 'mol-1',
    categoryId: 'molhos',
    name: 'Ao Sugo com Manjericão',
    description: 'Molho de tomate fresco com manjericão.',
    price: 20.00,
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
  {
    id: 'mol-2',
    categoryId: 'molhos',
    name: 'Bechamel',
    description: 'Molho branco clássico.',
    price: 20.00,
    image: 'https://images.unsplash.com/photo-1589113182023-7176141d2872?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
  {
    id: 'mol-3',
    categoryId: 'molhos',
    name: 'Frango Desfiado ao Molho de Tomate',
    description: 'Frango desfiado suculento ao molho de tomate artesanal.',
    price: 30.00,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
  {
    id: 'mol-4',
    categoryId: 'molhos',
    name: 'Funghi',
    description: 'Molho cremoso de funghi secchi.',
    price: 30.00,
    image: PRODUCT_IMAGES['mol-4'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
  {
    id: 'mol-5',
    categoryId: 'molhos',
    name: 'Strogonoff',
    description: 'Molho de strogonoff tradicional.',
    price: 30.00,
    image: PRODUCT_IMAGES['mol-5'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
  {
    id: 'mol-6',
    categoryId: 'molhos',
    name: 'Bolonhesa',
    description: 'Molho bolonhesa com carne moída magra.',
    price: 35.00,
    image: PRODUCT_IMAGES['mol-6'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
  {
    id: 'mol-7',
    categoryId: 'molhos',
    name: 'Carne de Panela',
    description: 'Molho de carne de panela desfiada.',
    price: 35.00,
    image: PRODUCT_IMAGES['mol-7'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
  {
    id: 'mol-8',
    categoryId: 'molhos',
    name: '4 Queijos',
    description: 'Molho cremoso com mix de 4 queijos.',
    price: 35.00,
    image: PRODUCT_IMAGES['mol-8'] || 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=800&auto=format&fit=crop',
    available: true,
    type: 'encomenda',
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Mariana Silva',
    comment: 'As marmitas são deliciosas e super práticas para o meu dia a dia corrido!',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?u=mariana',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'João Pedro',
    comment: 'Melhor custo-benefício que já encontrei. O desconto progressivo ajuda muito!',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?u=joao',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: '1',
    title: 'Combo 10 Marmitas',
    description: 'Peça 10 marmitas e pague apenas R$ 20,00 cada (R$ 200 total)!',
    image: 'https://images.unsplash.com/photo-1543353071-873f17a7a088?q=80&w=1200&auto=format&fit=crop',
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Combo 15 Marmitas',
    description: 'Acima de 15 marmitas, cada uma sai por R$ 19,00 (R$ 285 total)!',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=1200&auto=format&fit=crop',
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Oferta Coxinha Fit',
    description: 'Leve 3 Coxinhas de Frango Fit por apenas R$ 24,00!',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?q=80&w=1200&auto=format&fit=crop',
    active: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_PROFILE: BusinessProfile = {
  name: 'Lev & Fit 🌿',
  instagram: 'lovfitcongelados',
  phone: '5548991764001',
  bio: 'Marmitas Congeladas Saudáveis 🥗\n📍 Entregamos em Floripa e Grande Florianópolis\n🚚 Entrega a combinar • 🏠 Retirada no local',
  stats: {
    posts: 28,
    followers: '2.021',
    following: 211,
  },
  isOpen: true,
};

export const BUSINESS_CONFIG = {
  phone: '5548991764001', // Telefone pessoal atualizado
  instagram: 'lovfitcongelados',
};
